language: python
python:
  - 3.6
install: true
addons:
  ssh_known_hosts: 118.89.65.154
before_install:
- openssl aes-256-cbc -K $encrypted_b0e4a20bf5fb_key -iv $encrypted_b0e4a20bf5fb_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
script:
  - pwd
  - bash script/deploy.sh