language: python
python:
- 3.7
install: true
addons:
  ssh_known_hosts: 118.89.65.154
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 key
- ssh-add key
deploy:
  provider: script
  script: bash script/deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_b0e4a20bf5fb_key -iv $encrypted_b0e4a20bf5fb_iv
  -in id_rsa.enc -out id_rsa -d
